- name: automerge
  description: Automatically merge once required checks pass
  color: 0E8A16
- name: no automerge
  description: Block automatic merging
  color: F0F008
- name: wip
  description: Work in progress
  color: 80FFFF
- name: good-first-issue
  color: 7057ff
- name: needs-triage
  description: Needs triage
  color: 5319E7
- name: needs-rfc
  description: Needs a more detailed RFC before implementation
  color: D53802
- name: blocked
  description: Completion of issue is blocked by some other work
  color: d52202
  
- name: kind/bug
  color: 0052CC
- name: kind/feat
  color: 0052CC
- name: kind/cleanup
  color: 0052CC
- name: kind/refactor
  color: 0052CC
- name: kind/security
  color: 0052CC
- name: kind/docs
  color: 0052CC
- name: kind/regression
  color: 0052CC
- name: kind/sentry
  color: 0052CC
- name: kind/performance
  color: 0052CC

- name: size/xs
  color: 2C8604
- name: size/s
  color: 2C8604
- name: size/m
  color: 2C8604
- name: size/l
  color: 2C8604
- name: size/xl
  color: 2C8604

- name: priority/p2
  description: Low priority awaits more user feedback
  color: FBCA04
- name: priority/p1
  description: Regular issue. Prioritized per sprint
  color: FBCA04
- name: priority/p0
  description: Critical issue
  color: FBCA04

- name: triage/needs-information
  color: 5319E7
- name: triage/not-reproducible
  color: 5319E7
- name: triage/unresolved
  color: 5319E7

- name: area/ci
  color: d73a4a
- name: area/plugin-pb
  color: d73a4a
- name: area/plugin-sdk/go
  color: d73a4a
- name: area/plugin-sdk/python
  color: d73a4a
- name: area/plugin-sdk/javascript
  color: d73a4a
- name: area/plugin-sdk/java
  color: d73a4a
- name: area/cli
  color: d73a4a

- name: area/website/frontend
  color: F9D0C4
- name: area/hub/infra
  color: F9D0C4
- name: area/hub/backend
  color: F9D0C4
- name: area/hub/frontend
  color: F9D0C4
- name: area/hub/design
  color: F9D0C4
- name: area/cloud/infra
  color: F9D0C4
- name: area/cloud/backend
  color: F9D0C4
- name: area/cloud/frontend
  color: F9D0C4
- name: area/cloud/design
  color: F9D0C4

- name: area/new-plugin
  color: d73a4a
- name: area/plugin/source/other
  color: 006B75
- name: area/plugin/source/aws
  color: 006B75
- name: area/plugin/source/gcp
  color: 006B75
- name: area/plugin/source/azure
  color: 006B75
- name: area/plugin/source/k8s
  color: 006B75
- name: area/plugin/source/airtable
  color: 006B75
- name: area/plugin/source/alicloud
  color: 006B75
- name: area/plugin/source/awspricing
  color: 006B75
- name: area/plugin/source/azuredevops
  color: 006B75
- name: area/plugin/source/bitbucket
  color: 006B75
- name: area/plugin/source/cloudflare
  color: 006B75
- name: area/plugin/source/datadog
  color: 006B75
- name: area/plugin/source/digitalocean
  color: 006B75
- name: area/plugin/source/facebookmarketing
  color: 006B75
- name: area/plugin/source/fastly
  color: 006B75
- name: area/plugin/source/firestore
  color: 006B75
- name: area/plugin/source/gandi
  color: 006B75
- name: area/plugin/source/gcp
  color: 006B75
- name: area/plugin/source/github
  color: 006B75
- name: area/plugin/source/github
  color: 006B75
- name: area/plugin/source/gitlab
  color: 006B75
- name: area/plugin/source/googleads
  color: 006B75
- name: area/plugin/source/googleanalytics
  color: 006B75
- name: area/plugin/source/hackernews
  color: 006B75
- name: area/plugin/source/heroku
  color: 006B75
- name: area/plugin/source/homebrew
  color: 006B75
- name: area/plugin/source/hubspot
  color: 006B75
- name: area/plugin/source/jira
  color: 006B75
- name: area/plugin/source/launchdarkly
  color: 006B75
- name: area/plugin/source/meilisearch
  color: 006B75
- name: area/plugin/source/mixpanel
  color: 006B75
- name: area/plugin/source/mongodb
  color: 006B75
- name: area/plugin/source/notion
  color: 006B75
- name: area/plugin/source/okta
  color: 006B75
- name: area/plugin/source/oracle
  color: 006B75
- name: area/plugin/source/pagerduty
  color: 006B75
- name: area/plugin/source/plausible
  color: 006B75
- name: area/plugin/source/salesforce
  color: 006B75
- name: area/plugin/source/shopify
  color: 006B75
- name: area/plugin/source/slack
  color: 006B75
- name: area/plugin/source/snyk
  color: 006B75
- name: area/plugin/source/mysql
  color: 006B75
- name: area/plugin/source/postgresql
  color: 006B75
- name: area/plugin/source/render
  color: 006B75
- name: area/plugin/source/square
  color: 006B75
- name: area/plugin/source/stripe
  color: 006B75
- name: area/plugin/source/tailscale
  color: 006B75
- name: area/plugin/source/terraform
  color: 006B75
- name: area/plugin/source/typeform
  color: 006B75
- name: area/plugin/source/vault
  color: 006B75

- name: area/plugin/destination/gcs
  color: FEF2C0
- name: area/plugin/destination/gremlin
  color: FEF2C0
- name: area/plugin/destination/kafka
  color: FEF2C0
- name: area/plugin/destination/meilsearch
  color: FEF2C0
- name: area/plugin/destination/mongodb
  color: FEF2C0
- name: area/plugin/destination/mssql
  color: FEF2C0
- name: area/plugin/destination/mysql
  color: FEF2C0
- name: area/plugin/destination/neo4j
  color: FEF2C0
- name: area/plugin/destination/postgresql
  color: FEF2C0
- name: area/plugin/destination/s3
  color: FEF2C0
- name: area/plugin/destination/snowflake
  color: FEF2C0
- name: area/plugin/destination/sqlite
  color: FEF2C0



- name: area/policy/aws
  color: FBCA04
- name: area/policy/gcp
  color: FBCA04
- name: area/policy/azure
  color: FBCA04
- name: area/policy/k8s
  color: FBCA04
