group:
  # This will empty the workflows file
  # This needs to be the first thing that is synced
  - files:
      - source: workflows/empty
        dest: .github/workflows/
        deleteOrphaned: true
    repos: |
      cloudquery-policies/aws
      cloudquery-policies/azure
      cloudquery-policies/gcp
      cloudquery-policies/k8s
      cloudquery/cloudquery
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-azure
      cloudquery/cq-provider-digitalocean
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-k8s
      cloudquery/cq-provider-okta
      cloudquery/cq-provider-terraform
      cloudquery/cq-provider-template
      cloudquery/cq-provider-test
      cloudquery/helm-charts
  # All repos in cloudquery org
  - files:
    - source: CODEOWNERS
      dest: CODEOWNERS
    repos: |
      cloudquery/cloudquery
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-azure
      cloudquery/cq-provider-digitalocean
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-k8s
      cloudquery/cq-provider-okta
      cloudquery/cq-provider-terraform
      cloudquery/cq-provider-template
      cloudquery/cq-provider-test
      cloudquery/helm-charts


  # providers
  - files:
      - source: workflows/common
        dest: .github/workflows/
      - source: workflows/providers
        dest: .github/workflows/
        exclude: |
          test_integration.generated-cq-provider-k8s.yml
      - source: providers.golangci.yml
        dest: .golangci.yml
      - source: .github/renovate.json5
        dest: .github/renovate.json5
      - source: misc/providers/CONTRIBUTING.md
        dest: CONTRIBUTING.md
      - source: misc/providers/Makefile
        dest: Makefile
      - source: misc/providers/issue_reporting.md
        dest: docs/contributing/issue_reporting.md
      - source: misc/providers/PULL_REQUEST_TEMPLATE.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
      - source: misc/providers/.goreleaser.yaml
        dest: .goreleaser.yaml
    repos: |
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-azure
      cloudquery/cq-provider-digitalocean
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-k8s
      cloudquery/cq-provider-okta
      cloudquery/cq-provider-terraform
      cloudquery/cq-provider-template
      cloudquery/cq-provider-test

  # providers with terraform
  - files:
      - source: workflows/terraform
        dest: .github/workflows/
      - source: workflows/scripts
        dest: scripts/
      - source: misc/providers/PULL_REQUEST_TEMPLATE_terraform.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
    repos: |
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-azure

  # policies
  - files:
      - source: workflows/common/
        dest: .github/workflows/
        exclude: |
          lint_golang.yml
          issue_to_project.yml
      - source: workflows/policies
        dest: .github/workflows
    repos: |
      cloudquery-policies/aws
      cloudquery-policies/gcp
      cloudquery-policies/azure
      cloudquery-policies/k8s

# core
cloudquery/cloudquery:
  - source: workflows/common
    dest: .github/workflows/
  - source: workflows/repo-specific/cloudquery
    dest: .github/workflows/
  - source: .github/renovate.json5
    dest: .github/renovate.json5
  - source: misc/repo-specific/cloudquery/.goreleaser.yaml
    dest: .goreleaser.yaml

cloudquery/helm-charts:
  - source: workflows/common/
    dest: .github/workflows/
    exclude: |
      lint_golang.yml

cloudquery/cq-provider-sdk:
  - source: workflows/common
    dest: .github/workflows/
  - source: workflows/repo-specific/cq-provider-sdk
    dest: .github/workflows/


cloudquery/cq-provider-aws:
  - source: workflows/repo-specific/cq-provider-aws
    dest: .github/workflows/
