group:
  # This will empty the workflows file
  # This needs to be the first thing that is synced
  - files:
      - source: workflows/empty
        dest: .github/workflows/
        deleteOrphaned: true
    repos: |
      cloudquery-policies/aws
      cloudquery-policies/azure
      cloudquery-policies/gcp
      cloudquery-policies/k8s
      cloudquery/cloudquery
      cloudquery/cq-provider-sdk
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-azure
      cloudquery/cq-provider-digitalocean
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-k8s
      cloudquery/cq-provider-okta
      cloudquery/cq-provider-terraform
      cloudquery/cq-provider-template
      cloudquery/cq-provider-test
      cloudquery/helm-charts
  # All repos in cloudquery org
  - files:
    - source: CODEOWNERS
      dest: CODEOWNERS
    - source: .github/.kodiak.toml
      dest: .github/.kodiak.toml
    repos: |
      cloudquery/cloudquery
      cloudquery/cq-provider-sdk
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-azure
      cloudquery/cq-provider-digitalocean
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-k8s
      cloudquery/cq-provider-okta
      cloudquery/cq-provider-terraform
      cloudquery/cq-provider-template
      cloudquery/cq-provider-test
      cloudquery/helm-charts
      cloudquery/docs
      cloudquery/cq-website


  # providers
  - files:
      - source: workflows/common
        dest: .github/workflows/
      - source: workflows/providers
        dest: .github/workflows/
      - source: misc/providers/.golangci.yml
        dest: .golangci.yml
      - source: misc/providers/.gitignore
        dest: .gitignore
      - source: misc/common/renovate.json5
        dest: .github/renovate.json5
      - source: misc/providers/CONTRIBUTING.md
        dest: CONTRIBUTING.md
      - source: misc/providers/Makefile
        dest: Makefile
      - source: misc/providers/issue_reporting.md
        dest: docs/contributing/issue_reporting.md
      - source: misc/providers/PULL_REQUEST_TEMPLATE.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
      - source: misc/providers/.goreleaser.yaml
        dest: .goreleaser.yaml
    repos: |
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-azure
      cloudquery/cq-provider-digitalocean
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-k8s
      cloudquery/cq-provider-okta
      cloudquery/cq-provider-terraform
      cloudquery/cq-provider-template

  # providers with terraform
  - files:
      - source: workflows/scripts
        dest: scripts/
      - source: misc/providers/PULL_REQUEST_TEMPLATE_terraform.md
        dest: .github/PULL_REQUEST_TEMPLATE.md
    repos: |
      cloudquery/cq-provider-aws
      cloudquery/cq-provider-gcp
      cloudquery/cq-provider-azure

  # policies
  - files:
      - source: workflows/common/
        dest: .github/workflows/
        exclude: |
          lint_golang.yml
          issue_to_project.yml
      - source: workflows/policies
        dest: .github/workflows
      - source: .github/.kodiak.toml
        dest: .github/.kodiak.toml
      - source: misc/policies/CODEOWNERS
        dest: CODEOWNERS
    repos: |
      cloudquery-policies/aws
      cloudquery-policies/gcp
      cloudquery-policies/azure
      cloudquery-policies/k8s

  # docs and website
  - files:
      - source: misc/common/renovate.json5
        dest: .github/renovate.json5
    repos: |
      cloudquery/docs
      cloudquery/cq-website

# core
cloudquery/cloudquery:
  - source: misc/repo-specific/cloudquery/ISSUE_TEMPLATE
    dest: .github/ISSUE_TEMPLATE/
  - source: workflows/common
    dest: .github/workflows/
  - source: workflows/repo-specific/cloudquery
    dest: .github/workflows/
  - source: misc/repo-specific/cloudquery/renovate.json5
    dest: .github/renovate.json5
  - source: misc/repo-specific/cloudquery/.goreleaser.yaml
    dest: .goreleaser.yaml
  - source: misc/repo-specific/cloudquery/.goreleaser.prerelease.yaml
    dest: .goreleaser.prerelease.yaml
  - source: misc/common/CONTRIBUTING.md
    dest: .github/CONTRIBUTING.md
  - source: misc/common/PULL_REQUEST_TEMPLATE.md
    dest: .github/PULL_REQUEST_TEMPLATE.md
  - source: misc/common/.golangci.yml
    dest: .golangci.yml

cloudquery/helm-charts:
  - source: workflows/common/
    dest: .github/workflows/
    exclude: |
      lint_golang.yml
  - source: workflows/repo-specific/helm-charts
    dest: .github/workflows/

cloudquery/cq-provider-sdk:
  - source: workflows/common
    dest: .github/workflows/
  - source: workflows/repo-specific/cq-provider-sdk
    dest: .github/workflows/
  - source: misc/repo-specific/cq-provider-sdk/renovate.json5
    dest: .github/renovate.json5
  - source: misc/common/CONTRIBUTING.md
    dest: .github/CONTRIBUTING.md
  - source: misc/common/PULL_REQUEST_TEMPLATE.md
    dest: .github/PULL_REQUEST_TEMPLATE.md
  - source: misc/common/.golangci.yml
    dest: .golangci.yml


cloudquery/cq-provider-aws:
  - source: workflows/repo-specific/cq-provider-aws
    dest: .github/workflows/

cloudquery/cloudquery-issues:
  - source: workflows/common/issue_to_project.yml
    dest: .github/workflows/issue_to_project.yml

cloudquery/cq-provider-test:
  - source: workflows/common
    dest: .github/workflows/
  - source: workflows/providers
    dest: .github/workflows
    exclude: |
      lint_doc.yml
  - source: misc/providers/.golangci.yml
    dest: .golangci.yml
  - source: misc/providers/.gitignore
    dest: .gitignore
  - source: misc/common/renovate.json5
    dest: .github/renovate.json5
  - source: misc/providers/CONTRIBUTING.md
    dest: CONTRIBUTING.md
  - source: misc/providers/Makefile
    dest: Makefile
  - source: misc/providers/issue_reporting.md
    dest: docs/contributing/issue_reporting.md
  - source: misc/providers/PULL_REQUEST_TEMPLATE.md
    dest: .github/PULL_REQUEST_TEMPLATE.md
  - source: misc/providers/.goreleaser.yaml
    dest: .goreleaser.yaml

cloudquery/cq-website:
  - source: misc/repo-specific/cq-website/CODEOWNERS
    dest: CODEOWNERS