# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: lint_doc
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - '.github/**'
      - 'scripts/**'

jobs:
  lint_doc:
    name: Lint Provider Doc
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.17
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}
          token: ${{ secrets.GH_CQ_BOT }}
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - name: remove all docs
        run: |
          rm -f ./docs/tables/*.md
      - name: build-docs
        run: |
          go run ./docs/docs.go
      - uses: stefanzweifel/git-auto-commit-action@v4
        commit_message: "feat(docs): Sync docs changes"
