blank_issues_enabled: true
contact_links:
  - name: Ask a Question on Discord
    url: https://cloudquery.io/discord
    about: Ask questions and discuss with other community members.
  - name: CloudQuery Main Repository
    url: https://github.com/cloudquery/cloudquery
    about: Most CloudQuery features requests or bugs should be reported on the main repository.
