# DONT EDIT. This file is synced from https://github.com/cloudquery/.github/.github
name: lint_golang
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'terraform/**'
      - '.github/**'
      - 'scripts/**'

jobs:
  golangci:
    name: Lint with GolangCI
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.18
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.44.2
          args: --timeout 5m