rebaseMergeAllowed: true
squashMergeAllowed: true
mergeCommitAllowed: true
deleteBranchOnMerge: true
branchProtectionRules:
- pattern: main
  isAdminEnforced: false
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: false
  requiresStrictStatusChecks: false
  requiredStatusCheckContexts:
    - Validate PR title
    - Lint with GolangCI
    - checks (postgres:10, 1.18, ubuntu-latest)
    - unitests (postgres:10, 1.18, ubuntu-latest)
    - release-dry-run
- pattern: monorepo
  isAdminEnforced: false
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: false
  requiresStrictStatusChecks: false
  requiredStatusCheckContexts:
    - Validate PR title
    
    - Linter (cli)
    - Unit Tests (cli)

    - SQLPolicyTest (plugins/source/aws, postgres:10, 1.18, ubuntu-latest)
    - Linter (plugins/source/aws)
    - Unit Tests (plugins/source/aws)

    - SQLPolicyTest (plugins/source/azure, postgres:10, 1.18, ubuntu-latest)
    - Linter (plugins/source/azure)
    - Unit Tests (plugins/source/azure)

    - Linter (plugins/source/cloudflare)
    - Unit Tests (plugins/source/cloudflare)

    - Linter (plugins/source/digitalocean)
    - Unit Tests (plugins/source/digitalocean)

    - Linter (plugins/source/fuzz)
    - Unit Tests (plugins/source/fuzz)

    - SQLPolicyTest (plugins/source/gcp, postgres:10, 1.18, ubuntu-latest)
    - Linter (plugins/source/gcp)
    - Unit Tests (plugins/source/gcp)

    - Linter (plugins/source/github)
    - Unit Tests (plugins/source/github)

    - Linter (plugins/source/k8s)
    - Unit Tests (plugins/source/k8s)

    - Linter (plugins/source/okta)
    - Unit Tests (plugins/source/okta)

    - Linter (plugins/source/terraform)
    - Unit Tests (plugins/source/terraform)
