rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
deleteBranchOnMerge: true
branchProtectionRules:
- pattern: main
  isAdminEnforced: false
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: false
  requiresStrictStatusChecks: false
  requiredStatusCheckContexts:
    - Validate PR title
    - Lint with GolangCI
    - checks (postgres:latest, 1.17, ubuntu-latest)
    - unitests (postgres:latest, 1.17, ubuntu-latest)
    - release-dry-run
    - policy-tests (postgres:latest, 1.17, ubuntu-latest, aws)
    - policy-tests (postgres:latest, 1.17, ubuntu-latest, gcp)
    - policy-tests (postgres:latest, 1.17, ubuntu-latest, azure)
    - policy-tests (postgres:latest, 1.17, ubuntu-latest, k8s)
