rebaseMergeAllowed: false
squashMergeAllowed: true
mergeCommitAllowed: false
deleteBranchOnMerge: true
branchProtectionRules:
- pattern: main
  isAdminEnforced: false
  requiredApprovingReviewCount: 1
  requiresCodeOwnerReviews: false
  requiresStrictStatusChecks: false
  requiredStatusCheckContexts:
    - Validate PR title
    - Lint with GolangCI
    - Lint Provider Doc
    - test_unit (postgres:10, 1.17, ubuntu-latest)
    - release-dry-run
    - test_integration (postgres:10, 1.17, ubuntu-latest)
    - Terrafrom Plan