name: Add automerge labels
on:
  workflow_dispatch:
    inputs:
      syncPrs:
        description: "Add to sync PRs"
        required: false
        default: false
        type: boolean
      dependenciesPrs:
        description: "Add to dependencies updates PRs"
        required: false
        default: false
        type: boolean
      releasePrs:
        description: "Add to release PRs"
        required: false
        default: false
        type: boolean
jobs:
  add-automerge-labels:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add token to config.yaml
        uses: jacobtomlinson/gha-find-replace@657b0d1fe020da9943d1702b576f5d37d43b9c03
        with:
          find: GITHUB_TOKEN_VALUE
          replace: ${{ secrets.GH_CQ_BOT }}
          regex: false
          include: config.yaml

      - uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'npm'
          
      - run: npm ci

      - name: Add to sync PRs
        if: github.event.inputs.syncPrs == 'true'
        run: |
          npm run repo -- "tag" "--title" "Synced file" "automerge"

      - name: Add to dependencies updates PRs
        if: github.event.inputs.dependenciesPrs == 'true'
        run: |
          npm run repo -- "tag" "--title" "Update module" "automerge"

      - name: Add to release PRs
        if: github.event.inputs.releasePrs == 'true'
        run: |
          npm run repo -- "tag" "--title" "Release" "automerge"