name: Renovate
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"

concurrency:
  group: renovate-main
  cancel-in-progress: true

permissions:
  contents: read

env:
  RENOVATE_VERSION: "43.46.6"

jobs:
  renovate:
    runs-on: ubicloud-standard-4
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Restore Renovate cache
        uses: actions/cache/restore@v4
        with:
          path: /tmp/renovate/cache
          key: renovate-cache-${{ env.RENOVATE_VERSION }}
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v46.1.2
        with:
          renovate-version: ${{ env.RENOVATE_VERSION }}
          configurationFile: .github/self-hosted-renovate.js
          token: ${{ secrets.GH_CQ_BOT }}
        env:
          RENOVATE_GITHUB_ACTOR: ${{ github.actor }}
          RENOVATE_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LOG_LEVEL: 'debug'
      - name: Delete previous Renovate cache
        run: |
          gh cache delete "renovate-cache-${{ env.RENOVATE_VERSION }}" --repo "${{ github.repository }}" || true
        env:
          GH_TOKEN: ${{ secrets.GH_CQ_BOT }}
      - name: Save Renovate cache
        uses: actions/cache/save@v4
        with:
          path: /tmp/renovate/cache
          key: renovate-cache-${{ env.RENOVATE_VERSION }}
