name: Sync labels
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/labels.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
          repository: |
              cloudquery/cloudquery
              cloudquery/cloudquery-issues
              cloudquery/policies-premium
          token: ${{ secrets.GH_CQ_BOT }}
          prune: false
